name: A workflow for my Hello World file
on: push
jobs:
  your_npm_job_name:
    build:
      name: Hello world action
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ./action-a
          with:
            MY_NAME: "Mona"

